### ISSUE TITLE
Annotation for field that can't be filtered

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [studiomado/query-bundle#178]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| QueryBundle version  | 2.4

--- 

Create an entity annotation on its fields to declare if that field can't be filtered so if a request try to filter with that field the query bundle remove automatically that filter for example the field password. Now that can be done into the request listener but I think is better to Do it into the entity

**Comment by sensorario** [comment]
This is not a querybundle issue. I mean that data representation is made by JmsSerializer. Check you jms_serializer configuration. Here an example:

```
jms_serializer:
    metadata:
        directories:
            FooBar:
                namespace_prefix: "Foo\\BarBundle"
                path: "%kernel.root_dir%/serializer/FooBar"
    default_context:
        serialization:
            serialize_null: true
```

Inside folder ./app/serializer/FooBar/Model.User.yml you whould have the following file content:

```
Foo\BarBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        username:
            expose: true
        name:
            expose: true
        email:
            expose: true
        enabled:
            expose: true
        divisions:
            expose: true
        additional_filters:
            expose: true
```
